//AutoGenerated - 2025/6/24 18:27:20

using FishNet.Serializing;
using Unity.Collections;
using Unity.Entities;

namespace KillCam
{
    public partial class C_HandleNetworkMsgSystem {
        private void PoolNetworkEvents()
        {
            cmd = new EntityCommandBuffer(Allocator.Temp);
            while (dataQueue.Count > 0)
            {
                var reader = new Reader(dataQueue.Dequeue().Data, manager);
                var tick = manager.TimeManager.Tick;
                var msgType = (NetMsg)reader.ReadUInt32();
                switch (msgType)
                {
                    case NetMsg.S2C_NetSpawnPlayer :
							var S2C_NetSpawnPlayer  = new S2C_NetSpawnPlayer ();
							S2C_NetSpawnPlayer .Deserialize(reader);
							var ent = cmd.CreateEntity();
							cmd.AddComponent(ent, S2C_NetSpawnPlayer );
							cmd.AddComponent(ent, new NetMsgTag { Tick = tick, });
							break;

                }
            }

            cmd.Playback(EntityManager);
            cmd.Dispose();
        }
    }
}