//AutoGenerated - 2025/6/26 11:11:49

using FishNet.Serializing;
using Unity.Collections;
using Unity.Entities;

namespace KillCam
{
    public partial class S_HandleNetworkMsgSystem
    {
        private void PoolNetworkEvents()
        {
            var cmd = new EntityCommandBuffer(Allocator.Temp);
            while (waitHandles.Count > 0)
            {
                C2SMsg packet = waitHandles.Dequeue();
                var reader = new Reader(packet.Data, manager);
                var tick = reader.ReadUInt32();
                var msgType = (NetMsg)reader.ReadUInt32();
                switch (msgType)
                {
						case NetMsg.C2S_InputElement:
							var C2S_InputElement = new C2S_InputElement();
							C2S_InputElement.Deserialize(reader);
							var C2S_InputElement_Ent = cmd.CreateEntity();
							cmd.AddComponent(C2S_InputElement_Ent, C2S_InputElement);
							cmd.AddComponent(C2S_InputElement_Ent, new NetMsgTag());
							break;
                    
                }
            }
        }
    }
}