//AutoGenerated - 2025/6/24 18:27:20

using FishNet.Serializing;
using Unity.Collections;
using Unity.Entities;

namespace KillCam
{
    public partial class S_HandleNetworkMsgSystem
    {
        private void PoolNetworkEvents()
        {
            var cmd = new EntityCommandBuffer(Allocator.Temp);
            while (waitHandles.Count > 0)
            {
                C2SMsg packet = waitHandles.Dequeue();
                var reader = new Reader(packet.Data, manager);
                var tick = reader.ReadUInt32();
                var msgType = (NetMsg)reader.ReadUInt32();
                switch (msgType)
                {
                    case NetMsg.C2S_PlayerInputState :
							var C2S_PlayerInputState  = new C2S_PlayerInputState ();
							C2S_PlayerInputState .Deserialize(reader);
							var ent = cmd.CreateEntity();
							cmd.AddComponent(ent, C2S_PlayerInputState );
							cmd.AddComponent(ent, new NetMsgTag { Tick = tick, });
							break;

                }
            }
        }
    }
}